name: Test Concurrency Error 2
on:
  workflow_dispatch:
jobs:
  job_0:
    runs-on: test-for-metrics
    container:
      image: ascendai/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
      - run: sleep 60
  job_1:
    runs-on: test-for-metrics
    container:
      image: ascendai/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
      - run: sleep 60

