name: Test Sleep 3600
on:
  workflow_dispatch:
jobs:
  job_1:
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:latest
    steps:
      - name: Sleep
        run: |
          sleep 3600
