name: Test Sleep 3600
on:
  workflow_dispatch:
jobs:
  job_1:
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:8.0.0-910b-ubuntu22.04-py3.10
    steps:
      - name: Sleep
        run: |
          sleep 3600
